<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <RollForward>LatestMajor</RollForward>
    <DebugType>embedded</DebugType>
    <RootNamespace>WindowTextInjector</RootNamespace>
    <AssemblyName>WindowTextInjector</AssemblyName>
  </PropertyGroup>

</Project>
